### ISSUE TITLE
[BUG] Sparkle not working for all applications

### ISSUE THREAD

**Issue by jankkm** [updatest/feedback#7]
## Bug Description

Updatest does not show Sparkle updates for all apps that use it. There are different variants of the bug:

OBS.app:
Updatest shows Sparkle support but not the current update 32.0.1->32.0.2

A Better Finder Rename 12.app:
Updatest shows no Sparkle support at all.

Both offer an update in the app itself and they clearly use Sparkle as they have the Sparkle.framework bundled.

**Comment by HugeIRL** [comment]
Ah, that could be it. I wonder if these apps are using an older version of Sparkle that may not have required SUFeedURL, or some other variation. I'll explore this and see if Updatest can catch these too.

**Comment by jankkm** [comment]
I don't know what I was doing but actually the two applications in the first post do have the `SUFeedURL` key in the Info.plist.

OBS.app:
```
<key>SUFeedURL</key>
<string>https://obsproject.com/osx_update/updates_arm64_v2.xml</string>
```

A Better Finder Rename 12.app:
```
<key>SUFeedURL</key>
<string>http://www.publicspace.net/app/signed_abfr12.xml</string>
```

**Comment by HugeIRL** [comment]
Ah it's possible they have multiple feeds and that causes my logic to fail.

**Comment by HugeIRL** [comment]
@jankkm are you still experiencing this in Updatest 1.0.0.BETA (2042) ?

**Comment by jankkm** [comment]
Yes, "A Better Finder Rename 12.app" is still showing only with the `Brew` badge.

**Comment by HugeIRL** [comment]
@jankkm do you by chance have the download link for the app itself so I can install and test?

**Comment by jankkm** [comment]
> [@jankkm](https://github.com/jankkm) do you by chance have the download link for the app itself so I can install and test?

[Here you go](https://www.publicspace.net/download/ABFRX12.dmg)

**Comment by HugeIRL** [comment]
@jankkm I'm going to leave this issue open, but these issues should have been resolved in the build I released this morning. 1.0.0.BETA (2761)

**Comment by HugeIRL** [comment]
This one should be resolved. Please leave a comment if you still experience this issue.

**Comment by jankkm** [comment]
I am experiencing this right now with **WiFiSpoof**
There is a feed url in the Info.plist and it seems fine but Updatest still doesn't show an update:
https://sweetpproductions.com/products/wifispoof4/appcast.xml

Edit: This one is probably resolved by the new batch processing for Sparkle apps.

**Comment by jankkm** [comment]
**BBEdit** does not work either:
Feed: https://versioncheck.barebones.com/BBEdit.xml

**Comment by HugeIRL** [comment]
@jankkm found the bug for this one too I think and resolved in 1.0.0.BETA (5345). Let me know if it's still happening for you.

**Comment by jankkm** [comment]
@HugeIRL I have another one: Typora

There is an update in the Sparkle feed but Updatest only finds an in-app update but not the Sparkle update.

<img width="2564" height="1670" alt="Image" src="https://github.com/user-attachments/assets/17b0de7d-04e4-469a-b77c-9421473d2288" />

This is the feed url:
https://typora.io/releases/macos.xml

If I disable In-App updates in Updatest settings there is no update found.

**Comment by jankkm** [comment]
Refine.app doesn't work either. Feed url: https://refine.sh/release/stable/appcast.xml

**Comment by HugeIRL** [comment]
I'll take a look!

**Comment by jankkm** [comment]
Timemator.app has the same issue. Feed url: https://s3-eu-west-1.amazonaws.com/catforce-timemator/releases/appcast.xml

Updatest Version 1.2.0.BETA (5895)

**Comment by HugeIRL** [comment]
So I took a look at this and it appears (so far, I need to investigate further) that these updates are being gated by Sparkle itself, not Updatest. So something in Sparkle is hiding the update from Updatest, which could be a developer-specific thing like regional updates, etc.

I need more time to see if I can support these properly.

**Comment by jankkm** [comment]
> So I took a look at this and it appears (so far, I need to investigate further) that these updates are being gated by Sparkle itself, not Updatest. So something in Sparkle is hiding the update from Updatest, which could be a developer-specific thing like regional updates, etc.
> 
> I need more time to see if I can support these properly.

I don't see any gate here. For example Timemator.app:
```xml
❯ plutil -p "/Applications/Timemator.app/Contents/Info.plist"
{
  ...
  "SUFeedURL" => "https://s3-eu-west-1.amazonaws.com/catforce-timemator/releases/appcast.xml"
  "SUPublicDSAKeyFile" => "dsa_pub.pem"
}
```

```shell
❯ curl https://s3-eu-west-1.amazonaws.com/catforce-timemator/releases/appcast.xml
<?xml version="1.0" standalone="yes"?><rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
<channel>
<title>Timemator</title>

<item>
...

<item>
  <title>3.2.1</title>
  <pubDate>Sun, 3 January 2026 08:00:00 AM +0800</pubDate>
  <sparkle:minimumSystemVersion>10.15</sparkle:minimumSystemVersion>
  <sparkle:releaseNotesLink>https://timemator.com/support/release-notes/timemator/3.2.1/</sparkle:releaseNotesLink>
  <enclosure
    url="https://s3-eu-west-1.amazonaws.com/catforce-timemator/releases/Timemator_3.2.1.dmg"
    sparkle:version="187"
    sparkle:shortVersionString="3.2.1"
    length="26343936"
    type="application/octet-stream"
    sparkle:dsaSignature="MEYCIQCEpyRuXpCxhYp5TNf2j24F4XcDf8kzjFzNQfVAKY6AcQIhALQxMylCTNPmDfTmgvHb+1YPAVdae6ShAQaXC4HvkIlt"
  />
</item>

</channel></rss>
```
I think Updatest should be able to access and parse the feed. Or am I missing something?

**Comment by HugeIRL** [comment]
It might be hitting the timeout, I'll need to test and see what's going on. I'm committed to resolving this, it's just slow because I can't test sparkle updates programmatically and have to test these as the updates come out, unless I can directly install an older version.

**Comment by HugeIRL** [comment]
@jankkm how's this looking for you now with the official release? I believe I resolved this, if not please let me know.

**Comment by jankkm** [comment]
@HugeIRL
Things haven't changed much for me. Refine.app and Timemator.app still cannot be updated using Sparkle.

I noticed that [Timemator feed](https://s3-eu-west-1.amazonaws.com/catforce-timemator/releases/appcast.xml) does not have a \<sparkle:version\> tag but a **sparkle:version** attribute within the \<enclosure\> tag. Can Updatest deal with both?

The [Refine feed](https://refine.sh/release/stable/appcast.xml) seems pretty standard:
```xml
<rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
<channel>
<title>Refine</title>
<item>
<title>1.25</title>
<pubDate>Sun, 18 Jan 2026 14:54:45 -0800</pubDate>
<link>https://refine.sh</link>
<sparkle:fullReleaseNotesLink>https://refine.sh/changelog</sparkle:fullReleaseNotesLink>
<sparkle:phasedRolloutInterval>86400</sparkle:phasedRolloutInterval>
<sparkle:version>600</sparkle:version>
<sparkle:shortVersionString>1.25</sparkle:shortVersionString>
<sparkle:minimumSystemVersion>14</sparkle:minimumSystemVersion>
<sparkle:releaseNotesLink>https://refine.sh/changelog?ref=sparkle</sparkle:releaseNotesLink>
<enclosure url="https://refine.sh/release/stable/Refine_1.25.zip" length="32210033" type="application/octet-stream" sparkle:edSignature="Ewi2A6HbyMj1SIv6uoIEMx2EmteljQn1Gx3Nm6EDrDuxVHhX3w2GfzPcmCCSgnA8u0WEprkvgtVM8i8UrPv3Bg=="/>
</item>
</channel>
</rss>
```
Updatest shows the current **version 1.24 (580)** so the item in the feed clearly is applicable.

I do not think Updatest hits a timeout. There is no indication in the logs and I can see in a network monitor that the feed has been downloaded.

If you want to test it on your end here are links to the outdated versions of both applications (official source).
[Timemator 3.2.0](https://s3-eu-west-1.amazonaws.com/catforce-timemator/releases/Timemator_3.2.0.dmg)
[Refine 1.24](https://refine.sh/release/stable/Refine_1.24.zip)

**Comment by HugeIRL** [comment]
Thanks lemme test it on my side this should highlight exactly where the gap is.

**Comment by HugeIRL** [comment]
@jankkm working on Refine, but I found the issue for Timemator.

They use a DSA signed feed, which means it requires a public key to access the feed using Sparkle's internal library. This would work internally to the app, but not for Updatest as it wouldn't have access to this key.

Edit: To answer your question yes, Updatest can handle both because it delegates to the apps internal Sparkle implementation.

**Comment by HugeIRL** [comment]
@jankkm Ah! found the issue with Refine too.

They used phased rollouts:
```<sparkle:phasedRolloutInterval>86400</sparkle:phasedRolloutInterval>```

So they could be using a UUID approach and gating the update from your system based on your device UUID, or only allowing a small percentage of users to download the update, etc.

Edit: And if they're not (IE: you open the app and see Sparkle's update window for it) than that means they are for sure using some kind of device tracking (likely a UUID) that Updatest wouldn't have access to when it passes the connection over to Sparkle to check for updates. This is why you'd see no update in Updatest, but an update in the app itself.

**Comment by HugeIRL** [comment]
Both of these issues are likely repeated in the other apps you're not seeing for Sparkle updates. This is because Updatest delegates directly to the internal apps Sparkle implementation, and if developers have used things like DSA or phased roll outs, Updatest can't bypass these without building it's own fallback implementation to ignore the developers rules about their own update.

**Comment by jankkm** [comment]
I get it. I assumed that Updatest would just download and parse the sparkle feed but using the actual Sparkle implementation of the app makes a lot of sense.

In my opinion your mentioned fallback implementation would be good but you could argue that I should just use brew instead.

**Comment by HugeIRL** [comment]
Hey @jankkm I played around with this and came up with a compromise as sometimes Sparkle delegation could handle these updates, othertimes it could not. It seems it's up to the developer, so....

In Updatest 1.3.4 (6610) you should now see updates for these apps being displayed, however they will have a banner explaining they can't be updated automatically, and won't appear in the "Available" section of the Bulk Updater nor will they have the blue update arrow.

Example:

<img width="1986" height="750" alt="Image" src="https://github.com/user-attachments/assets/1f979736-dc94-4b47-a496-47da48ba440b" />

This should resolve 90%+ of the cases you found where Sparkle updates weren't found.

**Comment by jankkm** [comment]
I don't like it a lot but I guess those applications have to use homebrew then.

I thought about why I prefer Sparkle updates over brew and the main reason is that running application are being closed gracefully and then reopened. That is much better than running an outdated binary or closing the application manually. Maybe that's something Updatest could handle.
